@startuml
entity Order {
  +String id
  +String user_id
  +Date date
  +List<OrderItem> items
  +String status
  +Integer total_amount
  +String geo_zone
}

entity OrderItem {
  +String product_id
  +Integer quantity
  +Integer price
}

entity User {
  +String id
  +String name
}


Order "0.." -- "1" User : belongs_to
Order "1" -- "0..*" OrderItem : contains
@enduml