name: mongo-sharding

services:
  #  сервер конфигурации
  configSrv:
    image: dh-mirror.gitverse.ru/mongo:latest # docker образ
    container_name: configSrv
    ports: [ "27017:27017" ]
    volumes: [ config-data:/data/db ]
    command: [ "--configsvr","--replSet","config_server","--bind_ip_all","--port","27017" ]

  #  1-й шард
  shard1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1
    ports: [ "27018:27018" ]
    volumes: [ shard1-data:/data/db ]
    command: [ "--shardsvr","--replSet","shard1","--bind_ip_all","--port","27018" ]

  #  2-й шард
  shard2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2
    ports: [ "27019:27019" ]
    volumes: [ shard2-data:/data/db ]
    command: [ "--shardsvr","--replSet","shard2","--bind_ip_all","--port","27019" ]

  #  роутер
  mongos_router:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos_router
    restart: always
    ports: [ "27020:27020" ]
    command: [ "mongos","--configdb","config_server/configSrv:27017","--bind_ip_all","--port","27020" ]
    depends_on: [ configSrv,shard1,shard2 ]


  #  mongodb1:
  #    container_name: mongodb1
  #    image: dh-mirror.gitverse.ru/mongo:latest
  #    volumes:
  #      - mongodb1_data_container:/data/db

  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on: [ mongos_router ]
    ports: [ 8080:8080 ]
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"
#
#networks:
#  app-network:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 173.17.0.0/16


volumes:
  config-data:
  shard1-data:
  shard2-data:
#  mongodb1_data_container:
